### ISSUE TITLE
Exastroのホワイトペーパーの日本語版／英語版をコミュニティサイト上に掲載したい

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/docs#1]
ExastroコミュニティサイトTopのHandoutに掲載しているPDFを、
日本語版／英語版の両方、最新バージョンで再アップロードを実施していただきたいです。

日本語版の最新バージョンは下記です。
こちらを翻訳し、双方の掲載をお願いします。

[クラウドネイティブ化を促進するためのキーワード『攻めと守りの自動化』とは？.pdf](https://github.com/exastro-suite/docs/files/5908722/default.pdf)

■前回からのアップデート点
・「「守りの自動化」の実現で考えるべきポイントとは」の「４．調査」
　【変更前】ここでは、主に人による作業が中心となるが、情報収集の作業自動化することが可能だ。
　【変更後】ここでは、主に人による作業が中心となるが、情報収集の作業を自動化することが可能だ。
・「Exastro Operation Autonomy Support Engine」（Exastro OASE）
　【変更前】障害対応の切り分けで有効となる手段が、NEC がOSS として提供している「Exastro OASE」だ。
　【変更後】障害対応の切り分けで有効となる手段が、オープンソースソフトウェア(OSS)の「Exastro OASE」だ。
・「複数のルールリストを管理する」
　【変更前】そのため、各サービス毎や、インフラ等、メンテナンスし易い状態にカスタマイズできる。
　【変更後】そのため、例えばサービス単位に管理するなど、利用者の組織構造に応じて管理粒度を設定できる。
・「複数のルールリストを管理する」
　【変更前】さらに、「グループ毎にアクセスを制御する」の特徴とも関連するが、ルールリスト毎に、アクセス制御の設定が可能なため、管理者を分けてメンテナンスしていくことも可能である。
　【変更後】さらに、ルールリスト毎に、アクセス制御の設定が可能なため、管理者を分けてメンテナンスしていくことも可能である。
・「Exastro IT Automation」（Exastro ITA）
　【変更前】作業実行において有効な手段が、同じくNEC がOSS として提供している「Exastro ITA」だ。
　【変更後】作業実行において有効な手段が、同じくオープンソースソフトウェア(OSS)の「Exastro ITA」だ。
・「Exastro IT Automation」（Exastro ITA）
　【変更前】従来のモノリシックなシステムだけでなく、Terraform 等と連携することで、クラウドネイティブなシステムに対しても実行が可能だ。
　【変更後】Red Hat Ansible Automation Platform(Ansible)やTerraform Enterprise(Terraform)といった自動化ソフトウェアを実行管理することが可能で、従来のモノリシックなシステムだけでなく、クラウドネイティブなシステムも対象となる。
・IaC をモジュール管理して再利用性を高める
　【変更前】IaC（Playbook等）は、一度のみの利用で使い捨ててしまうのは非常に勿体ない。
　【変更後】IaC（Playbook等）は、一度だけの利用で使い捨ててしまうのは非常に勿体ない。
・IaC をモジュール管理して再利用性を高める
　【変更前】予めそれらを細かくモジュール化し、管理しておくことで、再利用を行うことが可能となるのである。
　【変更後】予めそれらを細かくモジュール化し、管理しておくことで、再利用が可能となる。
・複数の自動化ソフトウェアを繋げて実行する
　【変更前】例えば、Red Hat Ansible Automation Platformでは、実行する対象のノード毎にhost_vars の作成が必要となるが、
　【変更後】例えば、Ansibleでは、実行する対象のノード毎にhost_vars の作成が必要となるが、

**Comment by JoachimLarsen** [comment]
大変お待たせしております。
更新内容と翻訳をしたにファイルにまとめました。
引き続きどうぞよろしくお願いいたします。

[攻めと守りの自動化　変更内容.xlsx](https://github.com/exastro-suite/docs/files/5909366/default.xlsx)
