### ISSUE TITLE
News Roomに記載してほしい

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/docs#2]
Exastro IT Automationが登場しているので、
News Roomに記載をお願いします。
※英語サイトも対象でお願いします。

https://jpn.nec.com/press/202102/20210217_01.html

**Comment by katokeita** [comment]
News Room日本語サイト更新しました。
https://exastro-suite.github.io/docs/newsroom_ja.html

見出しの翻訳をお願いします。
「NEC、ServiceNowを活用したITサービス運用を高度化するソリューションを販売開始」

**Comment by JoachimLarsen** [comment]
見出しはこちらでお願いします。
\\
NEC Launches solution for Advancing IT Service operations using ServiceNow.　
\\

**Comment by katokeita** [comment]
迅速な対応ありがとうございます。

News Room英語サイト更新しました。
https://exastro-suite.github.io/docs/newsroom.html
