### ISSUE TITLE
2月のウェビナーのアーカイブ・資料を掲載したい

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/docs#4]
２月に実施したウェビナーのアーカイブと資料の公開をお願いします。

■セミナーコード
Ex-C02-Lv2

■概要
よくありがちな【Web(DMZ)＋AP/DB(内部ネットワーク)】の3層モデルを利用し、Firewall (Fortigate)、Loadballancer (BigIP)、L3SW(cat3560)に順序良く、自動的に設定を追加するデモを実施しています。
NW機器に関する業務をお持ちの方にピッタリのコースです。

■アーカイブURL
https://youtu.be/Hl1NUpxMNKQ

■教材資料
①[Exastro × Ansibleでやってみよう♪ネットワーク機器の自動設定_PDF原稿.pdf](https://github.com/exastro-suite/docs/files/6039621/Exastro.x.Ansible._PDF.pdf)
②Qiita
https://qiita.com/medius/items/b75bf8b3032ad25378c6

**Comment by katokeita** [comment]
Ex-C02-Lv2 更新しました。
https://exastro-suite.github.io/it-automation-docs/webinar_ja.html
