### ISSUE TITLE
Webinerのリストを最新化したい

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/docs#5]
ウェビナーリストを更新したので、それをコミュニティサイトに反映してほしいです。

赤枠部分が更新箇所です。

![Exastroウェビナーリスト](https://user-images.githubusercontent.com/62239529/112092076-136d6580-8bda-11eb-8859-c3ec0cbf7dbf.jpg)

**Comment by katokeita** [comment]
Webinarリスト更新しました。
https://exastro-suite.github.io/it-automation-docs/webinar_ja.html
