### ISSUE TITLE
News Roomに追加をお願いしたいです(2/26の早めに公開を希望)

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/docs#6]
2/26早めに、以下をNewsRoomに追加をお願いします。

[題名]
ITmedia DX Summit Vol.7にて講演

[日時]
2021/3/11 15:00

[講演資料]
[ITmediaDXSummitVol7_クラウドネイティブの必需品「攻めと守りの自動化」とは.pdf](https://github.com/exastro-suite/docs/files/6194318/ITmediaDXSummitVol7_.pdf)

[講演動画]
https://youtu.be/Tk7dqrGmIb4
※3/26 0:00に公開されるスケジューリング設定済みです。

[イベントURL]
https://mag.executive.itmedia.co.jp/executive/special/ex210199/index.html

[その他]
参考までに、こんな表紙絵を作りました。
使っていただいてもOKですし、使っていただかなくてもOKです。
お任せします。
![hyoushi](https://user-images.githubusercontent.com/49502353/112255820-56950a80-8ca6-11eb-85fb-1a4247739baa.png)

**Comment by katokeita** [comment]
見出しと資料名の翻訳をお願いします。

■見出し
ITmedia DX Summit Vol.7にて講演

■資料名
クラウドネイティブの必需品「攻めと守りの自動化」とは

**Comment by JoachimLarsen** [comment]
■見出し
Presentation at ITmedia DX Summit Vol. 7

■資料名
Crucial for Cloud Native? Offensive and Defensive Automation

でお願いします。

**Comment by katokeita** [comment]
News Room 更新しました。
https://exastro-suite.github.io/docs/newsroom.html
https://exastro-suite.github.io/docs/newsroom_ja.html
